### ISSUE TITLE
登陆不上网站

### ISSUE THREAD

**Issue by sumafuture** [Clov614/sakuracat#1]
软件使用不了，网站也不登陆不上

**Comment by Clov614** [comment]
你使用的是官方的软件嘛，网站全部都打不开吗

**Comment by Clov614** [comment]
@sumafuture 在紧急维护中(等修吧)，建议使用第三方客户端，基本上不需要频繁更新订阅

**Comment by Lannister94** [comment]
我也登不上去了

**Comment by WhiteTear** [comment]
我也是，还有其它好用的魔法推荐下吗？（只用来学习）

**Comment by Cheng-Fang-do** [comment]
登不上去了，多久能修复好呢

**Comment by Clov614** [comment]
> 登不上去了，多久能修复好呢

应该快了吧，猫猫属于是最便宜好用的机场了没有之一，会被同行攻击(猜测）

**Comment by Clov614** [comment]
> 我也是，还有其它好用的魔法推荐下吗？（只用来学习）

好用的魔法很多，至于价格就...
且用且珍惜

**Comment by Clov614** [comment]
https://sakuracat-cdn002.com/
